### ISSUE TITLE
服务端渲染的场景下使用 cheerio 没有性能问题吗？

### ISSUE THREAD

**Issue by Youjingyu** [umijs/umi-server#18]
1. 建议只有用户使用到 postProcessHtml 时，才调用 cheerio.load 解析 html string。现在貌似无论用户是否使用 postProcessHtml，都会调用。
2. 使用 cheerio.load 是为了允许用户对 html string 做二次处理。如果能够拿到原始的 react string，而不是整个 html，可能会灵活些

**Comment by ycjcl868** [comment]
1. 拿到渲染后的 html 需要做很多处理，例如 [injectChunkMaps](https://github.com/umijs/umi-server/blob/master/packages/umi-server/src/utils.ts#L18) 为开启 dynamicImport 站点做渲染 preload 等。
2. load 只在内部调用一次，剩下的 postProcessHtml 不会再将 load html。

**Comment by Youjingyu** [comment]
1. 我的意思是，只有在用户在 options 中传递了  postProcessHtml 时，才调用 cheerio.load
2. 如果我能拿到 react 根组件的渲染结果，即 `<div id="root">...</div>` 这个字符串，就只需要再拼接上 injectChunkMaps 需要的内容，就行了，而不需要使用 cheerio 去解析整个 html，然后调用类 dom 方法去 insert
3. 现在之所以拿不到  react 根组件的渲染结果，我猜测是 umi 把整个 html build 出来了，所以 renderToString 拿到的是整个 html
4. 我理解服务端是不需要处理 `<div id="root">...</div>` 内部的内容的，如果只是为了拼接上 injectChunkMaps 需要的内容，我觉得拿到 `renderToString(<App />) ` 后，直接字符串拼接就行

**Comment by ycjcl868** [comment]
1. 确实 cheerio 会有损性能，这个之前是用的 html str 拼接的方式，后续考虑到拼接的复杂性及不确定性，改成 cheerio 方式。 [#9](https://github.com/umijs/umi-server/pull/9/files#diff-7733b9689015bcf5e2ba654b3517db3bR6-R16)

2. umi ssr 有些不同的是，除了 `<div id="root"></div>` 里的 str 外，会有很多用户自定义的 `headScript` 、`head` 包括一些 umi 注入的 script context。感觉整体渲染返回会更适合 umi 项目。

**Comment by Youjingyu** [comment]
理解。
我现在是魔改 umi，强行拿到了 `renderToString(<App />)`  的结果，然后服务端自己拼接

**Comment by Youjingyu** [comment]
基于用户不会操作 `<div id="root">...</div>` 内部内容的前提，cheerio.load 其实可以只解析排除 `<div id="root">...</div>` 这部分的 html，至少比解析真个 html 好得多。
我始终觉得在 ssr 渲染的场景下，做这种实时解析字符串的动作，性能问题很大。
并且我理解，要解决你说的场景，应该还有其它方法

**Comment by ycjcl868** [comment]
赞同，root 内容确实不应该经过 cheerio

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/68181704-3ee6b480-ffd3-11e9-9939-00005b2f64f2.png)
