### ISSUE TITLE
配置 dynamicImport 后，页面出现 loading 闪烁

### ISSUE THREAD

**Issue by Youjingyu** [umijs/umi-server#23]
配置 `umi-plugin-react` 的 dynamicImport 后，渲染流程为：
渲染服务器直出内容 -> 加载页面的异步资源  -> 页面内容被 dynamicImport 的 loading 状态替换  -> 异步资源加载成功 -> 正确渲染

在这个过程中，页面内容会整体被 loading 状态替换一次，造成闪烁，请问有解决方案吗？

**Comment by ycjcl868** [comment]
在解决，Component 和 dva model 的动态加载，都需要解决

**Comment by Youjingyu** [comment]
有什么临时解决方案吗？我先 hack 一下

**Comment by Youjingyu** [comment]
我理解，应该通过修改 umi 源码的某个部分，使 umi 在 ssr 场景下不渲染 loading，就能暂时解决

**Comment by Youjingyu** [comment]
umi 貌似是用 react-loadable 来做懒加载的，react-loadable 的服务端渲染做法是，提前在 html 中通过 script 标签加载异步的资源，从而避免 loading 状态。

我通过这种方式暂时解决了，不知道这种解决方式是否合理？

**Comment by Youjingyu** [comment]
是我搞错了，这样粗暴的处理，貌似还是不行，就算前置加载了异步资源，react-loadable 内部还是判断为资源在 loading 状态

**Comment by jokwei** [comment]
遇到了相同的问题，选择先暂时关闭dynamicImport，loading状态会recalculate style出现短暂白屏，等待好的解决方案
