### ISSUE TITLE
出错后会一直处于正在等待localhost的响应状态

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-server#25]
umi-server似乎表现出对代码的低容错率。
在home model中添加如下代码，添加一个1/5概率的错误，预渲染成功后，访问页面尝试触发这个错误，触发后会导致页面无法打开，一直处在等待服务器响应的状态。
if(!Math.floor(Math.random() * (5))){
  throw 'random error';
};
这个问题暂时可以通过try catch解决，但在真实项目这样未免太过苛刻，真实项目根本无法做到100%保证不出错。

**Comment by ycjcl868** [comment]
TODO 中，在 compose 里加个 monads 容错 。超时机制也要加
