### ISSUE TITLE
为什么将getInitialProps中的方法移入componentWillMount同样能够获得预渲染效果？？

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-server#31]
**而且在高并发情况下性能表现更好!**

![image](https://user-images.githubusercontent.com/42126331/68930828-2d1ec180-07ca-11ea-8afb-2e50a615f1ea.png)
![image](https://user-images.githubusercontent.com/42126331/68930832-2e4fee80-07ca-11ea-8cad-b0439ab58708.png)

**Comment by ycjcl868** [comment]
可以看下 react 16 对这个生命周期的描述，废弃 API
