### ISSUE TITLE
通过浏览器的页面切换按钮，切换路由，当前路由的getInitialProps执行了，但是目标路由的getInitialProps却没有执行

### ISSUE THREAD

**Issue by jin-benben** [umijs/umi-server#32]
比如我当前在a页面，通过浏览器的前进后退进入b页面，当我切换到b页面的时候，b页面的getInitialProps方法没有执行，a页面的确执行了

**Comment by whereiscode** [comment]
我也是遇到了这个问题

**Comment by williamnie** [comment]
getInitialProps只在服务器调用，在客户端需要写正常的dispatch，建议先看下ssr的原理介绍就明白了，[http://ykfe.net/guide/](http://ykfe.net/guide/)
