### ISSUE TITLE
eggexample使用压力测试工具测试，在一小时内5000次PV访问后，页面的加载速度在逐渐变慢

### ISSUE THREAD

**Issue by jimmywong123** [umijs/umi-server#35]
一开始是100ms等待时间，随着PV访问的增加，页面加载时间在逐渐的增加。
最后增加到1s以上，如果继续进行PV访问，加载时间还会继续增加。
已经删除了home model中的concat写法，确保数据不会无限增加。

![image](https://user-images.githubusercontent.com/42126331/69024009-e6b0a900-09fb-11ea-86ac-3d92775c35c3.png)

**Comment by ycjcl868** [comment]
有 dump 出哪的问题吗

**Comment by jimmywong123** [comment]
完全不知道问题出在哪里，目前猜测是预渲染代码内存在某种资源堆积，导致随着pv访问逐渐变慢

**Comment by jimmywong123** [comment]
目前egg的案例是无法运行的，在更新umi后貌似仍然存在几千次访问后的页面逐渐变慢，及内存逐渐增加的问题。

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/69446740-0b0bdd00-0d90-11ea-89af-e7161cc47064.png)

性能在这序列化的时候，有巨大损耗。

![image](https://user-images.githubusercontent.com/13595509/69446793-2545bb00-0d90-11ea-87b6-ea613bd089b1.png)


![image](https://user-images.githubusercontent.com/13595509/69449466-f3375780-0d95-11ea-8a95-f779e6d323fe.png)

**Comment by jimmywong123** [comment]
问题还是没有解决，这个问题只有在压力测试工具模拟几千几万次的PV后才会凸显出来。
