### ISSUE TITLE
koa服务端渲染运行yarn dev报错

### ISSUE THREAD

**Issue by s464446877** [umijs/umi-server#54]
## What happens?
1、下载umi+koa服务端渲染的代码，运行yarn dev报错，终端错误提示/sockjs-node/info activeRoute not found
2、我们这个是否有热更新呢

## 最小可复现仓库

> 请使用 `yarn create umi` 创建，并上传到你的 GitHub 仓库

## 复现步骤，错误日志以及相关配置
提示错误/sockjs-node/info activeRoute not found

## 相关环境信息

- **Umi 版本**：2.12.3
- **Node 版本**：10.16.2
- **操作系统**：macOS

**Comment by williamnie** [comment]
你是下载的umi-server项目中的例子跑的，还是你自己重新搭建的项目运行的？

**Comment by s464446877** [comment]
下载的例子跑的

**Comment by williamnie** [comment]
我这测试是没问题的，切换到和你一样的环境了，可以跑起来

**Comment by s464446877** [comment]
我再下一个最新的看看吧，我是上上周下的，近几天我看还在更新，如果dev可以跑起来是可以热更新的是吧

**Comment by williamnie** [comment]
查了查你的报错，重新安装下包吧，yarn 一下

**Comment by s464446877** [comment]
重新下了，可以了，谢谢
