### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by rfw** [umijs/umi-server#61]
## What happens?
ssr模式，控制台打印一下内容
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://fb.me/react-uselayouteffect-ssr for common fixes.
in ConnectFunction
in ConnectFunction
in Fragment
in u
in Context.Provider
in Context.Consumer
in Route
in f
in Context.Consumer
in Switch
in Fragment
in s
in Context.Provider
in Router
in StaticRouter
in Context.Provider
in Provider
in m
in div
in body
in html

- **Umi Version**: ^2.12.6
- **Node Version**: v12.13.1
- **umi-server Version**:  ^1.1.8

**Comment by ycjcl868** [comment]
Please disable `polyfill`
