### ISSUE TITLE
修改前端代码没有热更新

### ISSUE THREAD

**Issue by 104gogo** [umijs/umi-server#8]
试了一下，在 examples/eggjs 中修改了前端的代码，没有热更新。需要手动 npm run build 一下。
另外，clone 下来直接运行 npm run dev，会有找不到 public/umi.server.js 文件的错误提示。
记得，以前好像是支持的哇？

**Comment by ycjcl868** [comment]
![image](https://user-images.githubusercontent.com/13595509/67571809-75b50300-f767-11e9-9d23-a55da8dd8de5.png)


我这有热更新

**Comment by 104gogo** [comment]
请教下另外一个问题
我看 umi 在 build 的时候才会生成 `umi.server.js` ，那 dev 的时候怎么找到 `umi.server.js` 这个文件呢？因为现在本地运行，就提示找不到文件的错误。

**Comment by ycjcl868** [comment]
egg 启动先于 umi build，所以本地才启动时访问不到，刷新一次就好了

**Comment by 104gogo** [comment]
不行呐。。必须要手动 build 一下？

**Comment by ycjcl868** [comment]
`npm run dev` 执行 `umi dev`，是会 build 出 `umi.server.js` 的

**Comment by 104gogo** [comment]
嗯，我也是这样认为的

如果 build 在本地，我这里确实没有生成这个文件呐，而且开发的时候也没必要 build 出实际的文件吧

如果是 build 在内存里面的，但是读取的本地 `umi.server.js` 的话，那确实是找不到噢
```javascript
this.root = join(__dirname, '..', 'public');
this.umiServerPath = join(this.root, 'umi.server.js');
```

**Comment by 104gogo** [comment]
不好意思，项目开的太多了，8000端口被占用没发现
怪不得没有显示出 webpack 的打包信息..
